export const MY_TEMPLATES_SET_LIST = 'MY_TEMPLATES_SET_LIST';
export const MY_TEMPLATES_UPDATE_LIST = 'MY_TEMPLATES_UPDATE_LIST';
export const MY_TEMPLATES_TOGGLE_LOADING = 'MY_TEMPLATES_TOGGLE_LOADING';
export const MY_TEMPLATES_UPDATE_SEARCH_PARAMS =
  'MY_TEMPLATES_UPDATE_SEARCH_PARAMS';
