export const TEMPLATE_TOGGLE_LOADING = 'TEMPLATE_TOGGLE_LOADING';
export const TEMPLATE_SET_LIST_MAP = 'TEMPLATE_SET_LIST_MAP';
export const TEMPLATE_ADD_ITEM = 'TEMPLATE_ADD_ITEM';
export const TEMPLATE_SET_USER_TEMPLATES_IDS =
  'TEMPLATE_SET_USER_TEMPLATES_IDS';
